version: "3.3"
services:
  db:
    image: mongo:3.5
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
  web:
    image: yapi
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./data/yapi
        target: /yapi
